version: '1.0'

services:
  db:
    image: mysql:8.1.0
    restart: always
    ports:  
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - .mysql/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  netcore:
    image: app-cliente
    restart: always
    ports:
      - 5001:80
